### ISSUE TITLE
大哥，我这里有几个文件丢失了

### ISSUE THREAD

**Issue by akerdi** [SFantasy/WeiboReactNative#7]
我这里丢失了些文件夹，比如./app/Comment/index.js里面提到的require('./style)；木有找到啊，还是说如何？？

**Comment by SFantasy** [comment]
嗯，原来写在`Comment`里的，后来独立出`components/CommonListView`，那行代码应当删掉。

 see: https://github.com/SFantasy/WeiboReactNative/commit/2ba1d636f5a5aef6d02b2ff185c29d76716d2d42
